/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adaptations;
import java.sql.*; 
import javax.swing.*; // this the text for massage box
import net.proteanit.sql.DbUtils; // this for table 
/**
 *
 * @author Bahaa
 */
public class customer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(customer.class.getName());

    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CusName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TextSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ComDevice = new javax.swing.JComboBox<>();
        ComSearch = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CusAdress = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        CusDate = new javax.swing.JTextField();
        CusId = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        EmId = new javax.swing.JTextField();
        Comcat = new javax.swing.JComboBox<>();
        CusPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));

        jPanel1.setBackground(new java.awt.Color(39, 55, 77));

        jButton2.setBackground(new java.awt.Color(82, 109, 130));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(221, 230, 237));
        jButton2.setText("Remove");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        Clear.setBackground(new java.awt.Color(82, 109, 130));
        Clear.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(221, 230, 237));
        Clear.setText("Clear Inputs");
        Clear.addActionListener(this::ClearActionPerformed);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Back");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setBackground(new java.awt.Color(82, 109, 130));
        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(221, 230, 237));
        jButton5.setText("Update");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setBackground(new java.awt.Color(82, 109, 130));
        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(221, 230, 237));
        jButton6.setText("Add");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(221, 230, 237));
        jLabel10.setText("Type Device");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(221, 230, 237));
        jLabel11.setText("Price");

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        CusName.setBackground(new java.awt.Color(204, 204, 204));
        CusName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CusName.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(221, 230, 237));
        jLabel12.setText("Em_ID");

        TextSearch.setBackground(new java.awt.Color(204, 204, 204));
        TextSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TextSearch.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(82, 109, 130));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(221, 230, 237));
        jButton1.setText("Search");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        ComDevice.setBackground(new java.awt.Color(204, 204, 204));
        ComDevice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ComDevice.setForeground(new java.awt.Color(0, 0, 0));
        ComDevice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chooice", "شارب", "تورنيدو ", "يونيون آير", "فريش ", "كاريير " }));

        ComSearch.setBackground(new java.awt.Color(204, 204, 204));
        ComSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ComSearch.setForeground(new java.awt.Color(0, 0, 0));
        ComSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chooice\t", "All", "ID", "Name", "Date" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(221, 230, 237));
        jLabel13.setText("device category");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(221, 230, 237));
        jLabel2.setText("Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(221, 230, 237));
        jLabel5.setText("Phone");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(221, 230, 237));
        jLabel6.setText("Date");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(221, 230, 237));
        jLabel8.setText("ID");

        CusAdress.setBackground(new java.awt.Color(204, 204, 204));
        CusAdress.setColumns(20);
        CusAdress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CusAdress.setForeground(new java.awt.Color(0, 0, 0));
        CusAdress.setRows(5);
        CusAdress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(CusAdress);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(221, 230, 237));
        jLabel1.setText("customer");

        CusDate.setBackground(new java.awt.Color(204, 204, 204));
        CusDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CusDate.setForeground(new java.awt.Color(0, 0, 0));

        CusId.setBackground(new java.awt.Color(204, 204, 204));
        CusId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CusId.setForeground(new java.awt.Color(0, 0, 0));
        CusId.addActionListener(this::CusIdActionPerformed);

        Price.setBackground(new java.awt.Color(204, 204, 204));
        Price.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Price.setForeground(new java.awt.Color(0, 0, 0));

        EmId.setBackground(new java.awt.Color(204, 204, 204));
        EmId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EmId.setForeground(new java.awt.Color(0, 0, 0));

        Comcat.setBackground(new java.awt.Color(204, 204, 204));
        Comcat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Comcat.setForeground(new java.awt.Color(0, 0, 0));
        Comcat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chooice", "1.25 حصان", "2.5 حصان", "3 حصان", "7 حصان" }));

        CusPhone.setBackground(new java.awt.Color(204, 204, 204));
        CusPhone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CusPhone.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(221, 230, 237));
        jLabel7.setText("His Address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 131, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(158, 158, 158)
                                        .addComponent(jButton4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Price, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(jLabel11))
                                                .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel13)
                                                .addComponent(Comcat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                                    .addComponent(ComDevice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(EmId, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 155, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(CusDate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CusPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CusName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CusId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CusId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CusName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CusDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Price, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComDevice)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Comcat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(EmId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(Clear))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String str ;
    DBconn c = new DBconn();
    ResultSet rs ;
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);
        new main().setVisible(true);
            }//GEN-LAST:event_jButton4ActionPerformed

    private void CusIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusIdActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {

            String id  = CusId.getText().toString();
            String name = CusName.getText().toString();
            String phone = CusPhone.getText().toString();
            String adress = CusAdress.getText().toString();
            String date = CusDate.getText().toString();
            String device = ComDevice.getSelectedItem().toString();
            String categ = Comcat.getSelectedItem().toString();
            String price = Price.getText().toString();
            String EmployeeId = EmId.getText().toString();

            str = "insert into CUSTOMERS values ('"+id+"','"+name+"','"+phone+"','"+date+"','"+adress+"','"+device+"','"+categ+"','"+price+"','"+EmployeeId +"')";
            c.stat.executeQuery(str);
            JOptionPane.showMessageDialog(null, "Added Succeed Customer");
            
            CusName.setText("");
            CusDate.setText("");
            CusAdress.setText("");
            CusPhone.setText("");
            CusId.setText("");
            TextSearch.setText("");
            EmId.setText("");
            Price.setText("");
            ComDevice.setSelectedIndex(0);
            ComSearch.setSelectedIndex(0);
            Comcat.setSelectedIndex(0);
            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            String id  = CusId.getText().toString();
            String name = CusName.getText().toString();
            String phone = CusPhone.getText().toString();
            String adress = CusAdress.getText().toString();
            String date = CusDate.getText().toString();
            String device = ComDevice.getSelectedItem().toString();
            String categ = Comcat.getSelectedItem().toString();
            String price = Price.getText().toString();
            String EmployeeId = EmId.getText().toString();

            
            str = "UPDATE CUSTOMERS SET CUSNAME='"+name+
                    "',CUSPHONE='"+phone+
                    "', CUSDATE='"+date+
                    "', CUSADDRESS='" + adress +
                    "', TYPEDEVICE= '"+device+
                    "',DEVICECATEGORY='"+categ+
                    "', PRICE='"+ price +
                    "', EMID= '"+ EmployeeId +
                    "' WHERE CUSID='"+ id +"'";
            
            c.stat.executeQuery(str);
            JOptionPane.showMessageDialog(null, "Updated Succeed Customer");
            
            CusName.setText("");
            CusDate.setText("");
            CusAdress.setText("");
            CusPhone.setText("");
            CusId.setText("");
            TextSearch.setText("");
            EmId.setText("");
            Price.setText("");
            ComDevice.setSelectedIndex(0);
            Comcat.setSelectedIndex(0);
            ComSearch.setSelectedIndex(0);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
try {

            String id  = CusId.getText().toString();
            String name = CusName.getText().toString();
            String phone = CusPhone.getText().toString();
            String adress = CusAdress.getText().toString();
            String date = CusDate.getText().toString();
            String device = ComDevice.getSelectedItem().toString();
            String categ = Comcat.getSelectedItem().toString();
            String price = Price.getText().toString();
            String EmployeeId = EmId.getText().toString();

            str = "DELETE FROM CUSTOMERS WHERE CUSID='"+ id + "'";
            c.stat.executeQuery(str);
            JOptionPane.showMessageDialog(null, "Removed Succeed Customer");
            
            CusName.setText("");
            CusDate.setText("");
            CusAdress.setText("");
            CusPhone.setText("");
            CusId.setText("");
            TextSearch.setText("");
            EmId.setText("");
            Price.setText("");
            ComDevice.setSelectedIndex(0);
            ComSearch.setSelectedIndex(0);
            Comcat.setSelectedIndex(0);
            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
            CusName.setText("");
            CusDate.setText("");
            CusAdress.setText("");
            CusPhone.setText("");
            CusId.setText("");
            TextSearch.setText("");
            EmId.setText("");
            Price.setText("");
            ComDevice.setSelectedIndex(0);
            ComSearch.setSelectedIndex(0);
            Comcat.setSelectedIndex(0);
                }//GEN-LAST:event_ClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String Choice = ComSearch.getSelectedItem().toString();
            
            if (Choice.equals("All")){
                rs = c.stat.executeQuery("SELECT * FROM CUSTOMERS");
            }
            else if (Choice == "ID"){
                rs = c.stat.executeQuery("SELECT * FROM CUSTOMERS where CUSID='"+TextSearch.getText()+"'");
            }
            else if (Choice == "Name"){
                rs = c.stat.executeQuery("SELECT * FROM CUSTOMERS where CUSNAME='" +TextSearch.getText()+"'");
                
            }
            else if (Choice == "Date"){
                 rs = c.stat.executeQuery("SELECT * FROM CUSTOMERS where CUSDATE='"+TextSearch.getText()+"'");
            }else{
                JOptionPane.showMessageDialog(null, "Choose the search type");
            }

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {           
            String strId = (jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0)).toString();
            rs = c.stat.executeQuery("SELECT * FROM CUSTOMERS where CUSID='"+ strId +"'");
            if (rs.next()) {
                CusId.setText(rs.getString("CUSID"));
                CusName.setText(rs.getString("CUSNAME"));
                CusPhone.setText(rs.getString("CUSPHONE"));
                CusDate.setText(rs.getString("CUSDATE"));
                CusAdress.setText(rs.getString("CUSaddress"));
                EmId.setText(rs.getString("EMID"));
                Price.setText(rs.getString("PRICE"));
                ComDevice.setSelectedItem(rs.getString("TYPEDEVICE"));
                Comcat.setSelectedItem(rs.getString("DEVICECATEGORY"));
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new customer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JComboBox<String> ComDevice;
    private javax.swing.JComboBox<String> ComSearch;
    private javax.swing.JComboBox<String> Comcat;
    private javax.swing.JTextArea CusAdress;
    private javax.swing.JTextField CusDate;
    private javax.swing.JTextField CusId;
    private javax.swing.JTextField CusName;
    private javax.swing.JTextField CusPhone;
    private javax.swing.JTextField EmId;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField TextSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
