package adaptations;

import java.sql.*; 
import javax.swing.*; // this the text for massage box
import net.proteanit.sql.DbUtils; // this for table 

public class employe extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(employe.class.getName());

    /**
     * Creates new form 
     */
    public employe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        EmPhone = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        EmID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        EmName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ComSearch = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TextSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmAge = new javax.swing.JTextField();
        type_working = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(39, 55, 77));

        EmPhone.setBackground(new java.awt.Color(204, 204, 204));
        EmPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmPhone.setForeground(new java.awt.Color(0, 0, 0));

        jButton6.setBackground(new java.awt.Color(153, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Back");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton1.setBackground(new java.awt.Color(82, 109, 130));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(221, 230, 237));
        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        EmID.setBackground(new java.awt.Color(204, 204, 204));
        EmID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmID.setForeground(new java.awt.Color(0, 0, 0));
        EmID.addActionListener(this::EmIDActionPerformed);

        jButton2.setBackground(new java.awt.Color(82, 109, 130));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(221, 230, 237));
        jButton2.setText("Update");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(82, 109, 130));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(221, 230, 237));
        jButton3.setText("Remove");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(82, 109, 130));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(221, 230, 237));
        jButton4.setText("Clear inputs");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(221, 230, 237));
        jLabel1.setText("Name");

        jButton5.setBackground(new java.awt.Color(82, 109, 130));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(221, 230, 237));
        jButton5.setText("Search");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(221, 230, 237));
        jLabel2.setText("Phone");

        EmName.setBackground(new java.awt.Color(204, 204, 204));
        EmName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmName.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(221, 230, 237));
        jLabel3.setText("Type employee");

        ComSearch.setBackground(new java.awt.Color(204, 204, 204));
        ComSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ComSearch.setForeground(new java.awt.Color(0, 0, 0));
        ComSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chooice", "All", "ID", "Name", "Phone", " " }));
        ComSearch.addActionListener(this::ComSearchActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(221, 230, 237));
        jLabel5.setText("ID");

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        TextSearch.setBackground(new java.awt.Color(204, 204, 204));
        TextSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextSearch.setForeground(new java.awt.Color(0, 0, 0));
        TextSearch.addActionListener(this::TextSearchActionPerformed);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(221, 230, 237));
        jLabel7.setText("Employee");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(221, 230, 237));
        jLabel6.setText("Age");

        EmAge.setBackground(new java.awt.Color(204, 204, 204));
        EmAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmAge.setForeground(new java.awt.Color(0, 0, 0));

        type_working.setBackground(new java.awt.Color(204, 204, 204));
        type_working.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        type_working.setForeground(new java.awt.Color(0, 0, 0));
        type_working.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chooice", "موظف تركيب", "موظف صيانه", "رجل الأمن", "كول سنتر", " " }));
        type_working.addActionListener(this::type_workingActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComSearch, 0, 98, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(EmAge, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(type_working, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EmName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(EmID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(63, 63, 63)
                                .addComponent(jButton6)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jButton6))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(type_working, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    //++++++++++++++++++++++++++++++++++++++++++++++++
    String str ;
    DBconn c = new DBconn();
    ResultSet rs ;
    //++++++++++++++++++++++++++++++++++++++++++++++++
    
    private void TextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSearchActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        new main().setVisible(true);
            }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
                    //+++++++++++++++++++(CODE SQL)+++++++++++++++++++
                    str = "insert into EMPLOYEE values ('"+
                    EmID.getText()+"','"+
                    EmName.getText()+"','"+
                    EmPhone.getText()+"','"+
                    type_working.getSelectedItem()+"','"+
                    EmAge.getText()+"')";
                    //++++++++++++++++++++++++++++++++++++++++++++++++

                    c.stat.executeQuery(str);
                    JOptionPane.showMessageDialog(null, "Add Employee succeed !");
                    EmAge.setText("");
                    EmName.setText("");
                    EmID.setText("");
                    EmPhone.setText("");
                    type_working.setSelectedIndex(0);
        } catch (SQLException xe) {
            JOptionPane.showMessageDialog(null, xe.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EmIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
                    //++++++++++++++++++++++(CODE SQL)+++++++++++++++++                    
                    str = "UPDATE EMPLOYEE SET EMNAME='"+EmName.getText()
                    +"' , EMPHONE='"+EmPhone.getText()
                    +"' , TYPEEMPLOYEE='"+type_working.getSelectedItem()
                    +"' , AGE='"+EmAge.getText()
                    +"' WHERE EMID='" + EmID.getText() + "'"; 
                    //++++++++++++++++++++++++++++++++++++++++++++++++

                    c.stat.executeQuery(str);
                    JOptionPane.showMessageDialog(null, "Updated Employee succeed !");
                    EmAge.setText("");
                    EmName.setText("");
                    EmID.setText("");
                    EmPhone.setText("");
                    type_working.setSelectedIndex(0);
        } catch (SQLException xe) {
            JOptionPane.showMessageDialog(null, xe.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
                    //++++++++++++++++++++++(CODE SQL)++++++++++++++++
                    str = "DELETE FROM EMPLOYEE WHERE EMID='"+EmID.getText() + "'";
                    //++++++++++++++++++++++++++++++++++++++++++++++++
                    
                    c.stat.executeQuery(str);
                    JOptionPane.showMessageDialog(null, "Removed Employee succeed !");
                    EmAge.setText("");
                    EmName.setText("");
                    EmID.setText("");
                    EmPhone.setText("");
                    type_working.setSelectedIndex(0);
        } catch (SQLException xe) {
            JOptionPane.showMessageDialog(null, xe.getMessage());
        }    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String Choice = ComSearch.getSelectedItem().toString();
            
            if (Choice.equals("All")){
                rs = c.stat.executeQuery("SELECT * FROM EMPLOYEE");
            }
            else if (Choice == "ID"){
                rs = c.stat.executeQuery("SELECT * FROM EMPLOYEE where EMID='"+TextSearch.getText()+"'");
            }
            else if (Choice == "Name"){
                rs = c.stat.executeQuery("SELECT * FROM EMPLOYEE where EMNAME='" +TextSearch.getText()+"'");
            }
            else if (Choice == "Phone"){
                rs = c.stat.executeQuery("SELECT * FROM EMPLOYEE where EMPHONE='" +TextSearch.getText() + "'");
            }
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ComSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComSearchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        EmID.setText("");
        EmName.setText("");
        EmAge.setText("");
        EmPhone.setText("");
        TextSearch.setText("");
        ComSearch.setSelectedIndex(0);
        type_working.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            String strId = (jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0)).toString();
            rs = c.stat.executeQuery("SELECT * FROM EMPLOYEE where EMID='"+ strId +"'");
            if (rs.next()) {
                EmID.setText(rs.getString("EMID"));
                EmName.setText(rs.getString("EMNAME"));
                EmPhone.setText(rs.getString("EMPHONE"));
                EmAge.setText(rs.getString("AGE"));
                type_working.setSelectedItem(rs.getString("TYPEEMPLOYEE"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void type_workingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_workingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_workingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new employe().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComSearch;
    private javax.swing.JTextField EmAge;
    private javax.swing.JTextField EmID;
    private javax.swing.JTextField EmName;
    private javax.swing.JTextField EmPhone;
    private javax.swing.JTextField TextSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> type_working;
    // End of variables declaration//GEN-END:variables
}
