/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adaptations;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Bahaa
 */
public class Salary_calculation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Salary_calculation.class.getName());

    /**
     * Creates new form Salary_calculation
     */
    public Salary_calculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        Date = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        rate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Salaries = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        salAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        salname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        target = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        salID = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        datesal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextSearch = new javax.swing.JTextField();
        ComSearch = new javax.swing.JComboBox<>();
        RadoEmoloyee = new javax.swing.JRadioButton();
        RadoSalary = new javax.swing.JRadioButton();
        employee_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        type_working = new javax.swing.JComboBox<>();
        Totile = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Date.setBackground(new java.awt.Color(39, 55, 77));

        jButton5.setBackground(new java.awt.Color(153, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Back");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        rate.setBackground(new java.awt.Color(204, 204, 204));
        rate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rate.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(82, 109, 130));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(221, 230, 237));
        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton3.setBackground(new java.awt.Color(82, 109, 130));
        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(221, 230, 237));
        jButton3.setText("Search");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        Salaries.setBackground(new java.awt.Color(204, 204, 204));
        Salaries.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Salaries.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(221, 230, 237));
        jLabel5.setText("salaries");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(221, 230, 237));
        jLabel1.setText("Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(221, 230, 237));
        jLabel6.setText("rate");

        jLabel7.setBackground(new java.awt.Color(0, 51, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(221, 230, 237));
        jLabel7.setText("Calculating workers' salaries");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(221, 230, 237));
        jLabel2.setText("Age");

        salAge.setBackground(new java.awt.Color(204, 204, 204));
        salAge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salAge.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(221, 230, 237));
        jLabel3.setText("Type work");

        jButton2.setBackground(new java.awt.Color(82, 109, 130));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(221, 230, 237));
        jButton2.setText("Update");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        salname.setBackground(new java.awt.Color(204, 204, 204));
        salname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salname.setForeground(new java.awt.Color(0, 0, 0));
        salname.addActionListener(this::salnameActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(221, 230, 237));
        jLabel4.setText("Total Salaries");

        target.setBackground(new java.awt.Color(204, 204, 204));
        target.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        target.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(221, 230, 237));
        jLabel8.setText("ID");

        salID.setBackground(new java.awt.Color(204, 204, 204));
        salID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salID.setForeground(new java.awt.Color(0, 0, 0));
        salID.addActionListener(this::salIDActionPerformed);

        jButton4.setBackground(new java.awt.Color(82, 109, 130));
        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(221, 230, 237));
        jButton4.setText("Remove");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton6.setBackground(new java.awt.Color(82, 109, 130));
        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(221, 230, 237));
        jButton6.setText("Clear Inputs");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        datesal.setBackground(new java.awt.Color(204, 204, 204));
        datesal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datesal.setForeground(new java.awt.Color(0, 0, 0));
        datesal.addActionListener(this::datesalActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(221, 230, 237));
        jLabel9.setText("Date");

        TextSearch.setBackground(new java.awt.Color(204, 204, 204));
        TextSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextSearch.setForeground(new java.awt.Color(0, 0, 0));
        TextSearch.addActionListener(this::TextSearchActionPerformed);

        ComSearch.setBackground(new java.awt.Color(204, 204, 204));
        ComSearch.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ComSearch.setForeground(new java.awt.Color(0, 0, 0));
        ComSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chooice", "All", "Name", "Type Work", "Employee ID", "Date (salaries)", " ", " " }));

        RadoEmoloyee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RadoEmoloyee.setText("Get Employee");

        RadoSalary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RadoSalary.setText("Salary");
        RadoSalary.addActionListener(this::RadoSalaryActionPerformed);

        employee_id.setBackground(new java.awt.Color(204, 204, 204));
        employee_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employee_id.setForeground(new java.awt.Color(0, 0, 0));
        employee_id.addActionListener(this::employee_idActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(221, 230, 237));
        jLabel10.setText("EM_ID");

        type_working.setBackground(new java.awt.Color(204, 204, 204));
        type_working.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        type_working.setForeground(new java.awt.Color(0, 0, 0));
        type_working.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chooice", "موظف تركيب", "موظف صيانه", "رجل الأمن", "كول سنتر", " " }));
        type_working.addActionListener(this::type_workingActionPerformed);

        Totile.setBackground(new java.awt.Color(204, 204, 204));
        Totile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Totile.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(221, 230, 237));
        jLabel11.setText("Target");

        jButton7.setBackground(new java.awt.Color(82, 109, 130));
        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(221, 230, 237));
        jButton7.setText("Clac");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout DateLayout = new javax.swing.GroupLayout(Date);
        Date.setLayout(DateLayout);
        DateLayout.setHorizontalGroup(
            DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DateLayout.createSequentialGroup()
                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(DateLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(159, 159, 159)
                                .addComponent(jButton5))
                            .addGroup(DateLayout.createSequentialGroup()
                                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(DateLayout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(DateLayout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(DateLayout.createSequentialGroup()
                                                .addComponent(RadoEmoloyee)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(RadoSalary))
                                            .addComponent(TextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)))
                                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComSearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DateLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(datesal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(type_working, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DateLayout.createSequentialGroup()
                                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DateLayout.createSequentialGroup()
                                        .addGap(676, 676, 676)
                                        .addComponent(employee_id))
                                    .addGroup(DateLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(DateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(DateLayout.createSequentialGroup()
                                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DateLayout.createSequentialGroup()
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Totile, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(target, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Salaries, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(salAge, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        DateLayout.setVerticalGroup(
            DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employee_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salAge)
                    .addComponent(Salaries, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(target, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Totile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DateLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DateLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datesal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type_working, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadoEmoloyee)
                    .addComponent(RadoSalary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String str ,str2;
    DBconn c = new DBconn();
    ResultSet rs ;
    private void salnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salnameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new main().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void salIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //++++++++++++++++++++
        // This is Add Button
        //++++++++++++++++++++
        
        //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        String id = salID.getText().toString();
        String EMid = employee_id.getText().toString();
        String name = salname.getText().toString();
        String age = salAge.getText().toString();
        String targets = target.getText().toString();
        String rates = rate.getText().toString();
        String sal = Salaries.getText().toString();
        String TypeWork = type_working.getSelectedItem().toString();
        String Date = datesal.getText().toString();
        String total = Totile.getText().toString();
        //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        try {
            //++++++++++++++++++++++(CODE SQL)+++++++++++++++++++++++++++++
            str = "INSERT INTO SALARYES VALUES ('"+id+
                    "','"+EMid+
                    "','"+age+
                    "','"+name+
                    "','"+Date+
                    "','"+TypeWork+
                    "','"+sal+
                    "','"+rates+
                    "','"+targets+
                    "','"+total+"')";
            //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
            
            c.stat.executeQuery(str);
            JOptionPane.showMessageDialog(null, "Added Succeed Salary.");
            salID.setText("");
            employee_id.setText("");
            Salaries.setText("");
            salname.setText("");
            salAge.setText("");
            type_working.setSelectedIndex(0);
            datesal.setText("");
            rate.setText("");
            target.setText("");
            Totile.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //++++++++++++++++++++
        // This is Update Button
        //++++++++++++++++++++
        //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        String EMid = employee_id.getText().toString();
        String id = salID.getText().toString();
        String name = salname.getText().toString();
        String age = salAge.getText().toString();
        String targets = target.getText().toString();
        String rates = rate.getText().toString();
        String sal = Salaries.getText().toString();
        String TypeWork = type_working.getSelectedItem().toString();
        String Date = datesal.getText().toString();
        //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        try {
            //++++++++++++++++++++++(CODE SQL)+++++++++++++++++++++++++++++
            str = "UPDATE SALARYES SET ID='"+id+
                    "', EMID='"+EMid+
                    "', AGE='"+age+
                    "', NAME='"+name+
                    "', SDATE='"+Date+
                    "', TYPEWORK='"+TypeWork+
                    "', SALARYE='"+sal+
                    "', RATE='"+rates+
                    "', TARGET='"+targets+
                    "', TOTAL='"+Totile.getText().toString()+"' WHERE ID='"+id+"'";
            //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
            c.stat.executeQuery(str);
            JOptionPane.showMessageDialog(null, "Updated Succeed Salary.");
            salID.setText("");
            employee_id.setText("");
            Salaries.setText("");
            salname.setText("");
            salAge.setText("");
            type_working.setSelectedIndex(0);
            datesal.setText("");
            rate.setText("");
            target.setText("");
            Totile.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //++++++++++++++++++++
        // This is DELETE Button
        //++++++++++++++++++++
        
        //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        String id = salID.getText().toString();
        //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        try {
            //++++++++++++++++++++++(CODE SQL)+++++++++++++++++++++++++++++
            str = "DELETE FROM SALARYES WHERE ID='"+id+"'";
            //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
            
            c.stat.executeQuery(str);
            JOptionPane.showMessageDialog(null, "Removed Succeed Salary.");
            salID.setText("");
            employee_id.setText("");
            Salaries.setText("");
            salname.setText("");
            salAge.setText("");
            type_working.setSelectedIndex(0);
            datesal.setText("");
            rate.setText("");
            target.setText("");
            Totile.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            salID.setText("");
            employee_id.setText("");
            Salaries.setText("");
            salname.setText("");
            salAge.setText("");
            type_working.setSelectedIndex(0);
            datesal.setText("");
            Totile.setText("");
            rate.setText("");
            target.setText("");    }//GEN-LAST:event_jButton6ActionPerformed

    private void datesalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datesalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datesalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //================(Search)================================
        try {
            String choice = ComSearch.getSelectedItem().toString();
            if (RadoSalary.isSelected()){
                if (choice.equals("All")) {
                    rs = c.stat.executeQuery("SELECT * FROM SALARYES");
                }else if(choice.equals("Name")){
                    rs = c.stat.executeQuery("SELECT * FROM SALARYES WHERE NAME='"+TextSearch.getText().toString()+"'");
                }else if(choice.equals("type work")){  
                    rs = c.stat.executeQuery("SELECT * FROM SALARYES WHERE TYPEWORK='"+TextSearch.getText().toString()+"'");
                }else if (choice.equals("Employee ID")){
                    rs = c.stat.executeQuery("SELECT * FROM SALARYES WHERE EMID='"+TextSearch.getText().toString()+"'");
                }else if (choice.equals("Date (salaries)")){
                    rs = c.stat.executeQuery("SELECT * FROM SALARYES WHERE SDATE='"+TextSearch.getText().toString()+"'");
                }
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            }else if (RadoEmoloyee.isSelected()){
                if (choice.equals("All")) {
                    rs = c.stat.executeQuery("SELECT * FROM EMPLOYEE");
                }if (choice.equals("Name")){
                    rs = c.stat.executeQuery("SELECT * FROM EMPLOYEE WHERE EMNAME='"+TextSearch.getText().toString()+"'");
                }if(choice.equals("type work")){
                    rs = c.stat.executeQuery("SELECT * FROM EMPLOYEE WHERE TYPEEMPLOYEE='"+TextSearch.getText().toString()+"'");
                }else if (choice.equals("Employee ID")){
                    rs = c.stat.executeQuery("SELECT * FROM EMPLOYEE WHERE EMID='"+TextSearch.getText().toString()+"'");
                }
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            }               
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        //================(Search)================================

    }//GEN-LAST:event_jButton3ActionPerformed

    private void TextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSearchActionPerformed

    private void RadoSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadoSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadoSalaryActionPerformed

    private void employee_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employee_idActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try {
            String strId = (jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0)).toString();
            if (RadoEmoloyee.isSelected()){
                rs = c.stat.executeQuery("SELECT * FROM EMPLOYEE where EMID='"+ strId +"'");
                if (rs.next()){
                    employee_id.setText(rs.getString("EMID"));
                    salname.setText(rs.getString("EMNAME"));
                    salAge.setText(rs.getString("AGE"));
                    type_working.setSelectedItem(rs.getString("TYPEEMPLOYEE"));
                }
                
            }else if(RadoSalary.isSelected()){
                rs = c.stat.executeQuery("SELECT * FROM SALARYES where ID='"+ strId +"'");
                if (rs.next()){
                    salID.setText(rs.getString("ID"));
                    employee_id.setText(rs.getString("EMID"));
                    Salaries.setText(rs.getString("SALARYE"));
                    rate.setText(rs.getString("RATE"));
                    target.setText(rs.getString("TARGET"));
                    salname.setText(rs.getString("NAME"));
                    salAge.setText(rs.getString("AGE"));
                    type_working.setSelectedItem(rs.getString("TYPEWORK"));
                    datesal.setText(rs.getString("SDATE"));
                    Totile.setText(rs.getString("TOTAL"));

                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    

    }//GEN-LAST:event_jTable1MouseClicked

    private void type_workingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_workingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_workingActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        double total = 0;
        
        //=================(rate)========================
        double rates = Double.parseDouble(rate.getText()); 
        if (rates >= 7.0) {
            total += 2000 ;
        }else if (rates >= 5.0){
            total += 1200;
        }else {
            total += 0;
        }
        //===============================================
        //=================(target)========================
        double targets = Double.parseDouble(target.getText().toString());
        if (targets >= 75) {
            total += 2000;
        }else if (targets >= 50){
            total += 1500;
        }else if (targets >= 25){
            total += 1000;
        }else {
            total += 0;
        }
        //===============================================
        //=================(total)========================
        double salaryes = Double.parseDouble(Salaries.getText().toString());
        total += salaryes ;
        Totile.setText(String.valueOf(total));
        //===============================================
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Salary_calculation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComSearch;
    private javax.swing.JPanel Date;
    private javax.swing.JRadioButton RadoEmoloyee;
    private javax.swing.JRadioButton RadoSalary;
    private javax.swing.JTextField Salaries;
    private javax.swing.JTextField TextSearch;
    private javax.swing.JTextField Totile;
    private javax.swing.JTextField datesal;
    private javax.swing.JTextField employee_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField rate;
    private javax.swing.JTextField salAge;
    private javax.swing.JTextField salID;
    private javax.swing.JTextField salname;
    private javax.swing.JTextField target;
    private javax.swing.JComboBox<String> type_working;
    // End of variables declaration//GEN-END:variables
}
